# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apache Gossip™
email: dev@gossip.incubator.apache.org
description: > # this means to ignore newlines until "baseurl:"
  Apache Gossip™ protocol is a method for a group of nodes to discover and check the liveliness of a cluster.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gossip.incubator.apache.org" # the base hostname & protocol for your site
twitter_username: ApacheGossip
github_username:  apache/incubator-gossip
repository:  apache/incubator-gossip
latest_minor_release: 0.1.0-SNAPSHOT

# Build settings
markdown: kramdown
